services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      - db

  db:
    image: mysql:8.4
    environment:
      MYSQL_PORT: ${DB_PORT}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # env_file:
    #   - ./../.env.development
