services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"
    # env_file:
    #   - .env
